project:
  type: object
  properties:
    id:
      type: string
    project_name:
      type: string
    description:
      type: string
projects:
  type: array
  maxItems: 100
  items:
    $ref: "#/project"
