name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true

      - name: Check path
        run: pwd && ls -la

      - name: Install dependencies
        run: bundle install

      - name: Lint code for consistent style
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Install packages
        run: |
          sudo rm -rf /var/lib/apt/lists/* && \
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends -y \
            curl libjemalloc2 libvips42 gcc g++ make default-libmysqlclient-dev libyaml-dev mysql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true

      - name: Check path
        run: pwd && ls -la

      - name: Install dependencies
        run: bundle install

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run tests
        env:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
          DB_DATABASE: app_test
        run: rails test
