name: Deploy Swagger UI to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Check path
        run: pwd && ls -la

      - name: Expand $ref in OpenAPI
        run: |
          swagger-cli bundle ./docs/index.yaml --outfile ./docs/openapi.yaml --type yaml
  build:
    needs: prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
      - name: Install swagger-cli
        run: npm install -g swagger-cli
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/openapi.yaml
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          # 絶対パスを指定
          path: swagger-ui

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
